# Generated by Django 4.1.6 on 2023-02-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialities',
            options={'verbose_name_plural': 'Specialities'},
        ),
    ]
