# Generated by Django 4.1.6 on 2023-02-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teams_leader'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='team_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teams.teams'),
        ),
    ]
